//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndromedaV1.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AndromedaV1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rose_et_Bordeaux_Lumière_noire__Action_Vaporwave__Aventure_Logo_animé {
            get {
                object obj = ResourceManager.GetObject("Rose et Bordeaux Lumière noire  Action Vaporwave  Aventure Logo animé", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rose_et_Bordeaux_Lumière_noire__Action_Vaporwave__Aventure_Logo_animé__239_x_55_px_ {
            get {
                object obj = ResourceManager.GetObject("Rose et Bordeaux Lumière noire  Action Vaporwave  Aventure Logo animé (239 x 55 p" +
                        "x)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rose_et_Bordeaux_Lumière_noire__Action_Vaporwave__Aventure_Logo_animé__239_x_55_px___1_ {
            get {
                object obj = ResourceManager.GetObject("Rose et Bordeaux Lumière noire  Action Vaporwave  Aventure Logo animé (239 x 55 p" +
                        "x) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rose_et_Bordeaux_Lumière_noire__Action_Vaporwave__Aventure_Logo_animé__239_x_55_px___2_ {
            get {
                object obj = ResourceManager.GetObject("Rose et Bordeaux Lumière noire  Action Vaporwave  Aventure Logo animé (239 x 55 p" +
                        "x) (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rose_et_Bordeaux_Lumière_noire__Action_Vaporwave__Aventure_Logo_animé__239_x_55_px___4_ {
            get {
                object obj = ResourceManager.GetObject("Rose et Bordeaux Lumière noire  Action Vaporwave  Aventure Logo animé (239 x 55 p" +
                        "x) (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rose_et_Bordeaux_Lumière_noire__Action_Vaporwave__Aventure_Logo_animé__835_x_515_px_ {
            get {
                object obj = ResourceManager.GetObject("Rose et Bordeaux Lumière noire  Action Vaporwave  Aventure Logo animé (835 x 515 " +
                        "px)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rose_et_Bordeaux_Lumière_noire__Action_Vaporwave__Aventure_Logo_animé__835_x_515_px___1_ {
            get {
                object obj = ResourceManager.GetObject("Rose et Bordeaux Lumière noire  Action Vaporwave  Aventure Logo animé (835 x 515 " +
                        "px) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rose_et_Bordeaux_Lumière_noire__Action_Vaporwave__Aventure_Logo_animé__835_x_515_px___1_1 {
            get {
                object obj = ResourceManager.GetObject("Rose et Bordeaux Lumière noire  Action Vaporwave  Aventure Logo animé (835 x 515 " +
                        "px) (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rose_et_Bordeaux_Lumière_noire__Action_Vaporwave__Aventure_Logo_animé__835_x_515_px___2_ {
            get {
                object obj = ResourceManager.GetObject("Rose et Bordeaux Lumière noire  Action Vaporwave  Aventure Logo animé (835 x 515 " +
                        "px) (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rose_et_Bordeaux_Lumière_noire__Action_Vaporwave__Aventure_Logo_animé__835_x_515_px___3_ {
            get {
                object obj = ResourceManager.GetObject("Rose et Bordeaux Lumière noire  Action Vaporwave  Aventure Logo animé (835 x 515 " +
                        "px) (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
